config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root to: "home#index"
  resources :invoices
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  STATUS_CLASS = {
    :draft => "badge badge-secondary",
    :sent => "badge badge-primary",
    :paid => "badge badge-success"
  }

  def subtotal
    1000
  end

  def discount_calculated
    subtotal * (self.discount / 100.0)
  end

  def vat_calculated
    (subtotal - discount_calculated) * (self.vat / 100.0)
  end

  def total
    subtotal - discount_calculated + vat_calculated
  end

  def status_class
    STATUS_CLASS[self.status.to_sym]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index    
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[ show edit update destroy]
  before_action :authenticate_user!

  # GET /invoices or /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1 or /invoices/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Invoice No. #{@invoice.id}",
               page_size: 'A4',
               template: "invoices/show.html.erb",
               layout: "pdf.html",
               orientation: "Portrait",
               lowquality: true,
               zoom: 1,
               save_to_file: Rails.root.join('tmp', "premium_invoice_#{@invoice.id}.pdf"),
               dpi: 75
      end
    end
    if params[:format] == "pdf"
      SendReportMailer.send_report(@invoice.id).deliver_now
    end
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices or /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: "Invoice was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:to_email, :to_phone,:policy_no, :date_of_commencement_of_policy,:date_of_commencement_of_risk, :plan_and_policy,
                                      :date_of_maturity, :basic_sum_assured, :accidental_benefit_sum_assured, :premium_for_plan, :total_premium_amount_rs,
                                      :date_for_paid, :date_of_birth_of_assured, :age_of_the_life_assured, :nominee_name, :nominee_relation, :proposal_no,
                                      :date_of_proposal, :assured_full_name, :name_of_proposer, :address_of_proposer, :address_of_assured)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/home/index.html.erb
<% name = current_user.present? ? current_user.email : 'Stranger' %>

<h1>Welcome, <%= name %> </h1>

app/views/invoices/_form.html.erb
<%= form_with(model: invoice) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "assured_full_name" %>
        <%= form.text_field :assured_full_name, :required => true %>
      </div>
    </div>
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "name_of_proposer" %>
        <%= form.text_field :name_of_proposer, :required => true%>
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "address_of_proposer" %>
        <%= form.text_field :address_of_proposer, :required => true %>
      </div>
    </div>
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "address_of_assured" %>
        <%= form.text_field :address_of_assured, :required => true %>
      </div>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "Email" %>
        <%= form.text_field :to_email, :required => true %>
      </div>
    </div>
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "Mobile Number" %>
        <%= form.text_field :to_phone, :required => true %>
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "date_of_birth_of_assured" %>
        <%= form.text_field :date_of_birth_of_assured, placeholder: "21/12/2021", :required => true %>
      </div>
    </div>
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "age_of_the_life_assured" %>
        <%= form.text_field :age_of_the_life_assured, placeholder: "Age", :required => true %>
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "nominee_name" %>
        <%= form.text_field :nominee_name, :required => true%>
      </div>
    </div>
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "nominee_relation" %>
        <%= form.text_field :nominee_relation, :required => true %>
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "Policy Number" %>
        <%= form.text_field :policy_no, :required => true %>
      </div>
    </div>
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "date_of_commencement_of_policy" %>
        <%= form.text_field :date_of_commencement_of_policy, placeholder: "21/12/2021", :required => true %>
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "date_of_commencement_of_risk" %>
        <%= form.text_field :date_of_commencement_of_risk, placeholder: "21/12/2021", :required => true %>
      </div>
    </div>
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "plan_and_policy" %>
        <%= form.text_field :plan_and_policy, :required => true %>
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "date_of_maturity" %>
        <%= form.text_field :date_of_maturity, placeholder: "21/12/2021", :required => true %>
      </div>
    </div>
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "basic_sum_assured" %>
        <%= form.text_field :basic_sum_assured, :required => true%>
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "accidental_benefit_sum_assured" %>
        <%= form.text_field :accidental_benefit_sum_assured, :required => true %>
      </div>
    </div>
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "premium_for_plan" %>
        <%= form.text_field :premium_for_plan, :required => true %>
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "total_premium_amount_rs" %>
        <%= form.text_field :total_premium_amount_rs, :required => true %>
      </div>
    </div>
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "date_of_paid" %>
        <%= form.text_field :date_for_paid, placeholder: "21/12/2021", :required => true %>
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "proposal_no" %>
        <%= form.text_field :proposal_no, :required => true %>
      </div>
    </div>
    <div class="form-group col-md-6">
      <div class="field">
        <%= form.label "date_of_proposal" %>
        <%= form.text_field :date_of_proposal, placeholder: "21/12/2021", :required => true%>
      </div>
    </div>
  </div>  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoices</h1>

<table>
  <thead>
    <tr>
      <th>To email</th>
      <th>To phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.to_email %></td>
        <td><%= invoice.to_phone %></td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<div class="invoice-box">
  <table cellpadding="0" cellspacing="0">
    <tr class="top">
      <td colspan="4">
        <table>
          <tr>
            <td class="title">
              <%= image_tag wicked_pdf_asset_base64('bharti-axa-logo.svg') %>
            </td>
            <td style="text-align: center !important;">
              <b>BHARTI AXA LIFE INSURANCE COMPANY LIMITED</b>
              <p>Registered Office: 61/62, Kalpataru Synergy, Vakola, Santacruz (East), Mumbai 400055</p>
            </td>
            <td>
              <%= image_tag wicked_pdf_asset_base64('bharti-axa-logo.svg') %>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td colspan="4" class="center">
        <b>Policy Document</b>
        <p>Bharti AXA Life Sanjeevani</p>
      </td>
    </tr>
  </table>
  <div style="font-size:12px;">
    <p> 
      Bharti AXA Life Sanjeevani, a single premium group term life insurance policy (”the Policy”) 
      is  issued  by  Bharti  AXA  Life  Insurance  Company  Limited  ("the  Company")  pursuant  to  the  
      proposal of <b><%= @invoice.assured_full_name %></b> ("the Policyholder") dated <%= @invoice.created_at.strftime('%d/%m/%Y') %> and in consideration of payment of Premiums as set out in the Policy.
      The  Policy  has  been  effected  on  the  lives  of  the  Life  Insured  based  on  the  proposal  form, and  the  statements,  information,  data  and  evidence  furnished  by  the  Policyholder  and receipt of Coverage Premiums from the Policyholder.
      The Company agrees to provide the Coverage/(s) and pay Benefit(s) in accordance with the 
      terms of the Policy.
      The proposal together with the statements, information, data and evidence, already 
      furnished  or to be furnished and leading  to  the  effecting of  the  insurance  hereunder, giving 
      all the variations in the particulars of the Lives Insured in so far as such variations have any 
      bearing on the insurance effected from time to time, shall be and are hereby declared to be 
      the basis of the Policy.
      The terms printed on this and the following pages along with the Schedule as existing on the 
      date  of  issue  of  the  Policy  and  as  attached  herewith  and  any  endorsements  placed  on  the Policy form part of the Policy.
    </p>
  </div>
  <table class="table-border" style="font-size:12px;">
    <tr class="information">
      <td class="table-border">
        <b>Policy No.:</b>
        <p class="center"><%= @invoice.policy_no %></p>
        <b>Date of Commencement of Policy:</b>
        <p class="center"><%= @invoice.date_of_commencement_of_policy%></p>
        <b>Date of Commencement of Risk:</b>
        <p class="center"><%= @invoice.date_of_commencement_of_risk%></p>
        <b>Plan and Policy:</b>
        <p class="center">Bharti AXA Life Sanjeevani</p>
        <b>Date Of Maturity:</b>
        <p class="center"><%= @invoice.date_of_maturity%></p>
      </td>
      <td class="table-border">
        <b><p class="text-left">Basic Sum Assured Rs.:</p></b>
        <p><%= @invoice.basic_sum_assured%></p>
        <b><p class="text-left">Accident Benefit Sum Assured Rs.:</p></b>
        <p><%= @invoice.accidental_benefit_sum_assured%></p>
      </td>
      <td class="table-border">
        <b>Premium For Plan Rs.:</b>
        <p class="center"><%= @invoice.premium_for_plan%></p>
        <b>Total Premium Amount Rs.:</b>
        <p class="center"><%= @invoice.total_premium_amount_rs%></p>
      </td>
      <td class="table-border">
        <b>Date of Paid.:</b>
        <p class="center"><%= @invoice.date_for_paid%></p>
        <b>Mode of Payment:</b>
        <p class="center">Online</p>
        <b>Date of birth of the Life Assured</b>
        <p class="center"><%= @invoice.date_of_birth_of_assured%></p>
        <b>Age of the Life Assured</b>
        <p class="center"><%= @invoice.age_of_the_life_assured%></p>
        <b>Whether age Admitted?</b>
        <p class="center">Y</p>
      </td>      
    </tr>
    <tr class="table-border">
      <td colspan="3" class="table-border">
        <b>Nominee Under Section 39 of the Insurance Act, 1938:</b><br>
        <p><%= @invoice.nominee_name%><span style="margin-left:20px;"><%= @invoice.nominee_relation%></span></p>
      </td>
      <td>
        <table>
          <tr>
            <td>
              <b>Proposal No.:</b>
              <p> <%= @invoice.proposal_no%></p>
            </td>            
          </tr>
          <tr>
            <td>
              <b>Date Of Proposal:</b>
              <p><%= @invoice.date_of_proposal%></p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <b>Name & Address of the Proposer</b>
        <p><b><%= @invoice.name_of_proposer%></b></p>
        <%= @invoice.address_of_proposer%>
        <p></p>
      </td>
      <td colspan="2">
        <b>Name & Address of the Assured</b>
        <p><b><%= @invoice.assured_full_name%></b></p>
        <%= @invoice.address_of_assured%>
      </td>
    </tr>
  </table>
  <div class="table-border" style="margin-top:10px;">
    <div style="padding: 10px;">
      <b>Events on the happening of which benefits are payable:</b>Details are mentioned overleaf. 
    </div>
  </div>
  <table class="table-border" style="font-size:12px;">
    <tr class="table-border">
      <td class="table-border">
        To Whom Sum Assured payable
      </td>
      <td colspan="3" class="table-border align-left">
        The Proposer or Life Assured or his Assignee under Section 38 of the Insurance Act 1938 or Nominees under Section 39 of the Insurance Act 1938 ot proved Executors or Administrators or other Legal Representatives who should take out representation to his/her Estate or limited to the moneys payable under this Policy from any Court of any State or Territory of the Union of India.
      </td>      
    </tr>
    <tr class="table-border">
      <td class="table-border"> Period during which premium payable</td>
      <td colspan="3" class="table-border  align-left"> Till the stipulated due date of the payment of last premium or earlier death of the Life Assured.</td>
    </tr>
  </table>
  <table style="font-size:12px;">
    <tr>
      <td colspan="2" class="left">
        <b>Date:</b><%= @invoice.created_at.strftime('%d/%m/%Y') %> <br>
        <b>Examined By:</b>
      </td>
      <td></td>
      <td colspan="2" class="right">
        <%= image_tag wicked_pdf_asset_base64('signature.jpeg'), :style=>"height:70px;"%>
      </td>
    </tr>
  </table>
  <div class="center margin-top" style="font-size:12px;">
    <p><b>This receipt is electronically generated and no signature is required.</b></p>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <%= link_to root_path, class: "navbar-brand" do %>
        <i class="far fa-file-pdf"></i>
        <span class="m-l-2">Generate Invoice Pdf</span>
      <% end %>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

      </ul>

      <% if action_name.to_sym == :show %>
        <%= link_to 'Back', root_path, class: "btn btn-outline-secondary mx-2" %>
        <%= link_to 'DOWNLOAD PDF', invoice_path(::Invoice.find(params[:id]), format: :pdf), class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>

    </div>
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Invoice Generator</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
            </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeneratePdf</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style = "border: 3px solid blue; border-bottom: 10px solid blue;">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'layouts/navbar' %>
    <% if @invoice.present? %>
      <%= render "layouts/header" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PDFs - Ruby on Rails</title>
    <%= wicked_pdf_stylesheet_link_tag "invoices" %>
</head>
<body style="background-color: #c2c8d6;">
    <%= yield %>
</body>
</html>